version: '3'
services:
  mongodb:
    image: 'mongo:bionic'
    container_name: 'mongo-container'
    environment:
      - MONGO_INITDB_DATABASE=nobel
    volumes:
      - ./db:/data/db
    ports:
      - '27017:27017'
